import Head from 'next/head'
import { appConstant } from '../constant/app-constant'

export const MyHead = (props: any) => {
  return (
    <Head>
      <title>{props.title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href={`${appConstant.CONTEXT_PATH}/favicon.ico`} />
    </Head>
  )
}
