import Head from 'next/head'
import { useSelector } from 'react-redux'
import { appConstant } from '../constant/app-constant'
import { selectMainState } from '../redux/store/main-slice'

export const XHead = (props: any) => {
  const mainState = useSelector(selectMainState)
  return (
    <Head>
      <title>{mainState.title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href={`${appConstant.CONTEXT_PATH}/favicon.ico`} />
      <meta name="viewport" content="initial-scale=1, width=device-width" />
    </Head>
  )
}
